package com.smk.presensi.desktop.model;

import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * Model sederhana untuk mewakili jurnal mengajar guru.
 * Disesuaikan dengan kebutuhan auto-jurnal dari aplikasi desktop.
 */
public class JournalEntry {
    private Long id;
    private Long presensiId;
    private Long guruId;
    private String guruNama;
    private LocalDate tanggal;
    private String kelas;
    private String mapel;
    private String materi;
    private String statusKehadiran;
    private String catatan;
    private boolean autoGenerated;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getPresensiId() {
        return presensiId;
    }

    public void setPresensiId(Long presensiId) {
        this.presensiId = presensiId;
    }

    public Long getGuruId() {
        return guruId;
    }

    public void setGuruId(Long guruId) {
        this.guruId = guruId;
    }

    public String getGuruNama() {
        return guruNama;
    }

    public void setGuruNama(String guruNama) {
        this.guruNama = guruNama;
    }

    public LocalDate getTanggal() {
        return tanggal;
    }

    public void setTanggal(LocalDate tanggal) {
        this.tanggal = tanggal;
    }

    public String getKelas() {
        return kelas;
    }

    public void setKelas(String kelas) {
        this.kelas = kelas;
    }

    public String getMapel() {
        return mapel;
    }

    public void setMapel(String mapel) {
        this.mapel = mapel;
    }

    public String getMateri() {
        return materi;
    }

    public void setMateri(String materi) {
        this.materi = materi;
    }

    public String getStatusKehadiran() {
        return statusKehadiran;
    }

    public void setStatusKehadiran(String statusKehadiran) {
        this.statusKehadiran = statusKehadiran;
    }

    public String getCatatan() {
        return catatan;
    }

    public void setCatatan(String catatan) {
        this.catatan = catatan;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}
