package com.smk.presensi.desktop.model;

import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * Model sederhana untuk Penilaian Ulangan Harian (UH) di desktop app.
 * Dicocokkan dengan UlanganHarianResponse dari backend.
 */
public class UlanganHarian {
    private Long id;
    private Long guruId;
    private String guruNama;
    private Long kelasId;
    private String kelasNama;
    private Long jadwalId;
    private LocalDate tanggal;
    private String jenis; // TULIS / PRAKTIK
    private String mapel;
    private String materi;
    private String catatan;
    private Double nilaiRataRata;
    private Integer jumlahPeserta;
    private Integer jumlahRemedial;
    private boolean autoGenerated;
    private LocalDateTime createdAt;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getGuruId() {
        return guruId;
    }

    public void setGuruId(Long guruId) {
        this.guruId = guruId;
    }

    public String getGuruNama() {
        return guruNama;
    }

    public void setGuruNama(String guruNama) {
        this.guruNama = guruNama;
    }

    public Long getKelasId() {
        return kelasId;
    }

    public void setKelasId(Long kelasId) {
        this.kelasId = kelasId;
    }

    public String getKelasNama() {
        return kelasNama;
    }

    public void setKelasNama(String kelasNama) {
        this.kelasNama = kelasNama;
    }

    public Long getJadwalId() {
        return jadwalId;
    }

    public void setJadwalId(Long jadwalId) {
        this.jadwalId = jadwalId;
    }

    public LocalDate getTanggal() {
        return tanggal;
    }

    public void setTanggal(LocalDate tanggal) {
        this.tanggal = tanggal;
    }

    public String getJenis() {
        return jenis;
    }

    public void setJenis(String jenis) {
        this.jenis = jenis;
    }

    public String getMapel() {
        return mapel;
    }

    public void setMapel(String mapel) {
        this.mapel = mapel;
    }

    public String getMateri() {
        return materi;
    }

    public void setMateri(String materi) {
        this.materi = materi;
    }

    public String getCatatan() {
        return catatan;
    }

    public void setCatatan(String catatan) {
        this.catatan = catatan;
    }

    public Double getNilaiRataRata() {
        return nilaiRataRata;
    }

    public void setNilaiRataRata(Double nilaiRataRata) {
        this.nilaiRataRata = nilaiRataRata;
    }

    public Integer getJumlahPeserta() {
        return jumlahPeserta;
    }

    public void setJumlahPeserta(Integer jumlahPeserta) {
        this.jumlahPeserta = jumlahPeserta;
    }

    public Integer getJumlahRemedial() {
        return jumlahRemedial;
    }

    public void setJumlahRemedial(Integer jumlahRemedial) {
        this.jumlahRemedial = jumlahRemedial;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
}

