package com.smk.presensi.entity;

import com.smk.presensi.enums.JenisUh;
import jakarta.persistence.*;

import java.time.LocalDate;
import java.time.LocalDateTime;

@Entity
@Table(name = "ulangan_harian")
public class UlanganHarian {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "guru_id", nullable = false)
    private Guru guru;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "kelas_id", nullable = false)
    private Kelas kelas;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "jadwal_id")
    private JadwalMengajar jadwal;

    @Column(nullable = false)
    private LocalDate tanggal;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private JenisUh jenis;

    @Column(nullable = false)
    private String mapel;

    @Column(length = 500)
    private String materi;

    @Column(length = 500)
    private String catatan;

    @Column(name = "nilai_rata_rata")
    private Double nilaiRataRata;

    @Column(name = "jumlah_peserta")
    private Integer jumlahPeserta;

    @Column(name = "jumlah_remedial")
    private Integer jumlahRemedial;

    @Column(name = "auto_generated")
    private boolean autoGenerated;

    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    @PrePersist
    public void prePersist() {
        this.createdAt = LocalDateTime.now();
    }

    public Long getId() {
        return id;
    }

    public Guru getGuru() {
        return guru;
    }

    public void setGuru(Guru guru) {
        this.guru = guru;
    }

    public Kelas getKelas() {
        return kelas;
    }

    public void setKelas(Kelas kelas) {
        this.kelas = kelas;
    }

    public JadwalMengajar getJadwal() {
        return jadwal;
    }

    public void setJadwal(JadwalMengajar jadwal) {
        this.jadwal = jadwal;
    }

    public LocalDate getTanggal() {
        return tanggal;
    }

    public void setTanggal(LocalDate tanggal) {
        this.tanggal = tanggal;
    }

    public JenisUh getJenis() {
        return jenis;
    }

    public void setJenis(JenisUh jenis) {
        this.jenis = jenis;
    }

    public String getMapel() {
        return mapel;
    }

    public void setMapel(String mapel) {
        this.mapel = mapel;
    }

    public String getMateri() {
        return materi;
    }

    public void setMateri(String materi) {
        this.materi = materi;
    }

    public String getCatatan() {
        return catatan;
    }

    public void setCatatan(String catatan) {
        this.catatan = catatan;
    }

    public Double getNilaiRataRata() {
        return nilaiRataRata;
    }

    public void setNilaiRataRata(Double nilaiRataRata) {
        this.nilaiRataRata = nilaiRataRata;
    }

    public Integer getJumlahPeserta() {
        return jumlahPeserta;
    }

    public void setJumlahPeserta(Integer jumlahPeserta) {
        this.jumlahPeserta = jumlahPeserta;
    }

    public Integer getJumlahRemedial() {
        return jumlahRemedial;
    }

    public void setJumlahRemedial(Integer jumlahRemedial) {
        this.jumlahRemedial = jumlahRemedial;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }
}
