package com.smk.presensi.desktop.service;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.smk.presensi.desktop.model.JournalEntry;
import com.smk.presensi.desktop.model.Presensi;

import java.io.IOException;
import java.net.http.HttpResponse;
import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * Service helper untuk operasi jurnal guru.
 */
public class JournalService {
    private final ApiClient apiClient;
    private final Gson gson;

    public JournalService(ApiClient apiClient) {
        this.apiClient = apiClient;
        this.gson = new GsonBuilder()
                .registerTypeAdapter(LocalDateTime.class, new LocalDateTimeAdapter())
                .create();
    }

    /**
     * Membuat entri jurnal (manual ataupun auto).
     */
    public JournalEntry createJournalEntry(JournalEntry entry) throws IOException, InterruptedException {
        return postEntry("/guru/jurnal", entry);
    }

    /**
     * Membantu membuat entri auto berdasarkan data presensi guru.
     */
    public JournalEntry createAutoEntryFromPresensi(Presensi presensi,
                                                    String kelas,
                                                    String mapel,
                                                    String materi,
                                                    String catatanTambahan) throws IOException, InterruptedException {
        if (presensi == null || presensi.getUserId() == null) {
            throw new IllegalArgumentException("Presensi guru tidak valid untuk auto-jurnal");
        }

        JournalEntry entry = new JournalEntry();
        entry.setPresensiId(presensi.getId());
        entry.setGuruId(presensi.getUserId());
        entry.setGuruNama(presensi.getUsername());
        entry.setTanggal(presensi.getTanggal() != null ? presensi.getTanggal() : LocalDate.now());
        entry.setKelas(kelas);
        entry.setMapel(mapel);
        entry.setMateri(materi);
        entry.setStatusKehadiran(presensi.getStatus());
        entry.setCatatan(catatanTambahan);
        entry.setAutoGenerated(true);

        return createJournalEntry(entry);
    }

    private JournalEntry postEntry(String endpoint, JournalEntry entry) throws IOException, InterruptedException {
        String jsonBody = gson.toJson(entry);
        HttpResponse<String> response = apiClient.post(endpoint, jsonBody);

        if (response.statusCode() == 200 || response.statusCode() == 201) {
            return gson.fromJson(response.body(), JournalEntry.class);
        }

        throw new IOException("Failed to create journal entry: " + response.statusCode() + " - " + response.body());
    }
}
