package com.smk.presensi.desktop.service;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.reflect.TypeToken;
import com.smk.presensi.desktop.model.UlanganHarian;

import java.io.IOException;
import java.lang.reflect.Type;
import java.net.http.HttpResponse;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;

/**
 * Service untuk komunikasi Penilaian Ulangan Harian (UH) dengan backend.
 */
public class UlanganHarianService {

    private final ApiClient apiClient;
    private final Gson gson;

    public UlanganHarianService(ApiClient apiClient) {
        this.apiClient = apiClient;
        this.gson = new GsonBuilder()
                .registerTypeAdapter(LocalDateTime.class, new LocalDateTimeAdapter())
                .create();
    }

    public List<UlanganHarian> list(Long guruId, LocalDate start, LocalDate end) {
        try {
            StringBuilder endpoint = new StringBuilder("/akademik/uh");
            List<String> params = new ArrayList<>();
            if (guruId != null) {
                params.add("guruId=" + guruId);
            }
            DateTimeFormatter formatter = DateTimeFormatter.ISO_LOCAL_DATE;
            if (start != null) {
                params.add("startDate=" + start.format(formatter));
            }
            if (end != null) {
                params.add("endDate=" + end.format(formatter));
            }
            if (!params.isEmpty()) {
                endpoint.append("?").append(String.join("&", params));
            }

            HttpResponse<String> response = apiClient.get(endpoint.toString());
            if (response.statusCode() == 200) {
                Type listType = new TypeToken<List<UlanganHarian>>(){}.getType();
                return gson.fromJson(response.body(), listType);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return new ArrayList<>();
    }

    public UlanganHarian create(UlanganHarian uh) throws IOException, InterruptedException {
        String jsonBody = gson.toJson(toRequestBody(uh));
        HttpResponse<String> response = apiClient.post("/akademik/uh", jsonBody);
        if (response.statusCode() == 201 || response.statusCode() == 200) {
            return gson.fromJson(response.body(), UlanganHarian.class);
        }
        throw new IOException("Failed to create UH: " + response.statusCode() + " - " + response.body());
    }

    private UlanganHarianRequestBody toRequestBody(UlanganHarian uh) {
        return new UlanganHarianRequestBody(
                uh.getGuruId(),
                uh.getKelasId(),
                uh.getJadwalId(),
                uh.getTanggal(),
                uh.getJenis(),
                uh.getMapel(),
                uh.getMateri(),
                uh.getCatatan(),
                uh.getNilaiRataRata(),
                uh.getJumlahPeserta(),
                uh.getJumlahRemedial(),
                uh.isAutoGenerated()
        );
    }

    private static class UlanganHarianRequestBody {
        Long guruId;
        Long kelasId;
        Long jadwalId;
        LocalDate tanggal;
        String jenis;
        String mapel;
        String materi;
        String catatan;
        Double nilaiRataRata;
        Integer jumlahPeserta;
        Integer jumlahRemedial;
        boolean autoGenerated;

        UlanganHarianRequestBody(Long guruId,
                                 Long kelasId,
                                 Long jadwalId,
                                 LocalDate tanggal,
                                 String jenis,
                                 String mapel,
                                 String materi,
                                 String catatan,
                                 Double nilaiRataRata,
                                 Integer jumlahPeserta,
                                 Integer jumlahRemedial,
                                 boolean autoGenerated) {
            this.guruId = guruId;
            this.kelasId = kelasId;
            this.jadwalId = jadwalId;
            this.tanggal = tanggal;
            this.jenis = jenis;
            this.mapel = mapel;
            this.materi = materi;
            this.catatan = catatan;
            this.nilaiRataRata = nilaiRataRata;
            this.jumlahPeserta = jumlahPeserta;
            this.jumlahRemedial = jumlahRemedial;
            this.autoGenerated = autoGenerated;
        }
    }
}

