package com.smk.presensi.dto.jurnal;

import com.smk.presensi.enums.StatusPresensi;
import jakarta.validation.constraints.NotNull;

import java.time.LocalDate;

public record GuruJurnalRequest(
        @NotNull(message = "guruId wajib diisi")
        Long guruId,
        Long presensiId,
        Long kelasId,
        @NotNull(message = "tanggal wajib diisi")
        LocalDate tanggal,
        String mapel,
        String materi,
        StatusPresensi statusKehadiran,
        String catatan,
        boolean autoGenerated
) {
}
