package com.smk.presensi.dto.jurnal;

import com.smk.presensi.enums.StatusPresensi;

import java.time.LocalDate;
import java.time.LocalDateTime;

public record GuruJurnalResponse(
        Long id,
        Long guruId,
        String guruNama,
        Long presensiId,
        Long kelasId,
        String kelasNama,
        LocalDate tanggal,
        String mapel,
        String materi,
        StatusPresensi statusKehadiran,
        String catatan,
        boolean autoGenerated,
        LocalDateTime createdAt
) {
}
