package com.smk.presensi.service;

import com.smk.presensi.dto.jurnal.GuruJurnalRequest;
import com.smk.presensi.dto.jurnal.GuruJurnalResponse;
import com.smk.presensi.entity.Guru;
import com.smk.presensi.entity.GuruJurnal;
import com.smk.presensi.entity.Kelas;
import com.smk.presensi.entity.Presensi;
import com.smk.presensi.repository.GuruJurnalRepository;
import com.smk.presensi.repository.GuruRepository;
import com.smk.presensi.repository.KelasRepository;
import com.smk.presensi.repository.PresensiRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDate;
import java.util.List;
import java.util.stream.Collectors;

@Service
public class GuruJurnalService {

    private final GuruJurnalRepository guruJurnalRepository;
    private final GuruRepository guruRepository;
    private final PresensiRepository presensiRepository;
    private final KelasRepository kelasRepository;

    public GuruJurnalService(GuruJurnalRepository guruJurnalRepository,
                             GuruRepository guruRepository,
                             PresensiRepository presensiRepository,
                             KelasRepository kelasRepository) {
        this.guruJurnalRepository = guruJurnalRepository;
        this.guruRepository = guruRepository;
        this.presensiRepository = presensiRepository;
        this.kelasRepository = kelasRepository;
    }

    @Transactional
    public GuruJurnalResponse create(GuruJurnalRequest request) {
        Guru guru = guruRepository.findById(request.guruId())
                .orElseThrow(() -> new RuntimeException("Guru ID %d tidak ditemukan".formatted(request.guruId())));

        GuruJurnal jurnal = new GuruJurnal();
        jurnal.setGuru(guru);
        jurnal.setTanggal(request.tanggal());
        jurnal.setMapel(request.mapel());
        jurnal.setMateri(request.materi());
        jurnal.setStatusKehadiran(request.statusKehadiran());
        jurnal.setCatatan(request.catatan());
        jurnal.setAutoGenerated(request.autoGenerated());

        if (request.presensiId() != null) {
            Presensi presensi = presensiRepository.findById(request.presensiId())
                    .orElseThrow(() -> new RuntimeException("Presensi ID %d tidak ditemukan".formatted(request.presensiId())));
            jurnal.setPresensi(presensi);
            if (jurnal.getTanggal() == null) {
                jurnal.setTanggal(presensi.getTanggal());
            }
            if (request.kelasId() == null && presensi.getKelas() != null) {
                jurnal.setKelas(presensi.getKelas());
            }
            if (request.mapel() == null) {
                jurnal.setMapel(presensi.getMapel());
            }
            if (request.materi() == null) {
                jurnal.setMateri(presensi.getMateri());
            }
            if (request.statusKehadiran() == null) {
                jurnal.setStatusKehadiran(presensi.getStatus());
            }
        }

        if (request.kelasId() != null) {
            Kelas kelas = kelasRepository.findById(request.kelasId())
                    .orElseThrow(() -> new RuntimeException("Kelas ID %d tidak ditemukan".formatted(request.kelasId())));
            jurnal.setKelas(kelas);
        }

        GuruJurnal saved = guruJurnalRepository.save(jurnal);
        return toResponse(saved);
    }

    @Transactional(readOnly = true)
    public List<GuruJurnalResponse> list(Long guruId, LocalDate start, LocalDate end) {
        List<GuruJurnal> data;
        if (guruId != null && start != null && end != null) {
            data = guruJurnalRepository.findByGuru_IdAndTanggalBetweenOrderByTanggalDesc(guruId, start, end);
        } else if (guruId != null) {
            data = guruJurnalRepository.findByGuru_IdOrderByTanggalDesc(guruId);
        } else {
            data = guruJurnalRepository.findAll();
        }
        return data.stream().map(this::toResponse).collect(Collectors.toList());
    }

    private GuruJurnalResponse toResponse(GuruJurnal jurnal) {
        return new GuruJurnalResponse(
                jurnal.getId(),
                jurnal.getGuru().getId(),
                jurnal.getGuru().getNama(),
                jurnal.getPresensi() != null ? jurnal.getPresensi().getId() : null,
                jurnal.getKelas() != null ? jurnal.getKelas().getId() : null,
                jurnal.getKelas() != null ? jurnal.getKelas().getNama() : null,
                jurnal.getTanggal(),
                jurnal.getMapel(),
                jurnal.getMateri(),
                jurnal.getStatusKehadiran(),
                jurnal.getCatatan(),
                jurnal.isAutoGenerated(),
                jurnal.getCreatedAt()
        );
    }
}
