package com.smk.presensi.service;

import com.smk.presensi.dto.uh.UlanganHarianRequest;
import com.smk.presensi.dto.uh.UlanganHarianResponse;
import com.smk.presensi.entity.Guru;
import com.smk.presensi.entity.JadwalMengajar;
import com.smk.presensi.entity.Kelas;
import com.smk.presensi.entity.UlanganHarian;
import com.smk.presensi.repository.GuruRepository;
import com.smk.presensi.repository.JadwalMengajarRepository;
import com.smk.presensi.repository.KelasRepository;
import com.smk.presensi.repository.UlanganHarianRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDate;
import java.util.List;
import java.util.stream.Collectors;

@Service
public class UlanganHarianService {

    private final UlanganHarianRepository ulanganHarianRepository;
    private final GuruRepository guruRepository;
    private final KelasRepository kelasRepository;
    private final JadwalMengajarRepository jadwalMengajarRepository;

    public UlanganHarianService(UlanganHarianRepository ulanganHarianRepository,
                                GuruRepository guruRepository,
                                KelasRepository kelasRepository,
                                JadwalMengajarRepository jadwalMengajarRepository) {
        this.ulanganHarianRepository = ulanganHarianRepository;
        this.guruRepository = guruRepository;
        this.kelasRepository = kelasRepository;
        this.jadwalMengajarRepository = jadwalMengajarRepository;
    }

    @Transactional
    public UlanganHarianResponse create(UlanganHarianRequest request) {
        UlanganHarian uh = new UlanganHarian();
        apply(request, uh);
        return toResponse(ulanganHarianRepository.save(uh));
    }

    @Transactional(readOnly = true)
    public List<UlanganHarianResponse> list(Long guruId, LocalDate start, LocalDate end) {
        List<UlanganHarian> data;
        if (guruId != null && start != null && end != null) {
            data = ulanganHarianRepository.findByGuru_IdAndTanggalBetween(guruId, start, end);
        } else if (guruId != null) {
            data = ulanganHarianRepository.findByGuru_IdAndTanggalBetween(guruId, LocalDate.now().minusMonths(1), LocalDate.now().plusDays(1));
        } else {
            data = ulanganHarianRepository.findAll();
        }
        return data.stream().map(this::toResponse).collect(Collectors.toList());
    }

    private void apply(UlanganHarianRequest request, UlanganHarian uh) {
        Guru guru = guruRepository.findById(request.guruId())
                .orElseThrow(() -> new RuntimeException("Guru ID %d tidak ditemukan".formatted(request.guruId())));
        Kelas kelas = kelasRepository.findById(request.kelasId())
                .orElseThrow(() -> new RuntimeException("Kelas ID %d tidak ditemukan".formatted(request.kelasId())));
        uh.setGuru(guru);
        uh.setKelas(kelas);
        uh.setTanggal(request.tanggal());
        uh.setJenis(request.jenis());
        uh.setMapel(request.mapel());
        uh.setMateri(request.materi());
        uh.setCatatan(request.catatan());
        uh.setNilaiRataRata(request.nilaiRataRata());
        uh.setJumlahPeserta(request.jumlahPeserta());
        uh.setJumlahRemedial(request.jumlahRemedial());
        uh.setAutoGenerated(request.autoGenerated());
        if (request.jadwalId() != null) {
            JadwalMengajar jadwal = jadwalMengajarRepository.findById(request.jadwalId())
                    .orElseThrow(() -> new RuntimeException("Jadwal ID %d tidak ditemukan".formatted(request.jadwalId())));
            uh.setJadwal(jadwal);
        } else {
            uh.setJadwal(null);
        }
    }

    private UlanganHarianResponse toResponse(UlanganHarian uh) {
        return new UlanganHarianResponse(
                uh.getId(),
                uh.getGuru().getId(),
                uh.getGuru().getNama(),
                uh.getKelas().getId(),
                uh.getKelas().getNama(),
                uh.getJadwal() != null ? uh.getJadwal().getId() : null,
                uh.getTanggal(),
                uh.getJenis(),
                uh.getMapel(),
                uh.getMateri(),
                uh.getCatatan(),
                uh.getNilaiRataRata(),
                uh.getJumlahPeserta(),
                uh.getJumlahRemedial(),
                uh.isAutoGenerated(),
                uh.getCreatedAt()
        );
    }
}
