package com.smk.presensi.dto.uh;

import com.smk.presensi.enums.JenisUh;
import jakarta.validation.constraints.NotNull;

import java.time.LocalDate;

public record UlanganHarianRequest(
        @NotNull(message = "guruId wajib diisi")
        Long guruId,
        @NotNull(message = "kelasId wajib diisi")
        Long kelasId,
        Long jadwalId,
        @NotNull(message = "tanggal wajib diisi")
        LocalDate tanggal,
        @NotNull(message = "jenis UH wajib diisi")
        JenisUh jenis,
        @NotNull(message = "mapel wajib diisi")
        String mapel,
        String materi,
        String catatan,
        Double nilaiRataRata,
        Integer jumlahPeserta,
        Integer jumlahRemedial,
        boolean autoGenerated
) {
}
