package com.smk.presensi.dto.uh;

import com.smk.presensi.enums.JenisUh;

import java.time.LocalDate;
import java.time.LocalDateTime;

public record UlanganHarianResponse(
        Long id,
        Long guruId,
        String guruNama,
        Long kelasId,
        String kelasNama,
        Long jadwalId,
        LocalDate tanggal,
        JenisUh jenis,
        String mapel,
        String materi,
        String catatan,
        Double nilaiRataRata,
        Integer jumlahPeserta,
        Integer jumlahRemedial,
        boolean autoGenerated,
        LocalDateTime createdAt
) {
}
